servers: ['plex','emby'] # You can only keep one ['plex'] or ['emby'].
plex:
  host: http://127.0.0.1:32400
  token: plex token
emby:
  host: http://127.0.0.1:8096
  api_key: emby api_key 
  path_mapping: # Assuming your plex and emby are on different servers, then you may need to do path mapping
    enable: true
    rules:
      - from: /share/SSD1T/03cd2/115
        to: /mnt/user/CloudDrive/115
      - from: /share/SSD1T/03cd2/aliyun
        to: /mnt/user/CloudDrive/aliyundrive
MONITOR_FOLDER:
  - /share/SSD1T/03cd2/115/Movies
  - /share/SSD1T/03cd2/115/TVs
  - /share/SSD1T/03cd2/aliyun/Movies
  - /share/SSD1T/03cd2/aliyun/TVs