cd2:
  host: http://192.168.xxx.xxx:19798
  user: your@mail.com
  password: your-password
servers: ['plex','emby']
plex:
  host: http://192.168.xxx.xxxx:32400
  token: your-plex-token
  isfile_based_scanning: true # 基于局部文件的扫描，而不是扫描变更文件的父目录；否则扫描变更文件的父目录。如果变更的是目录，则扫描变更目录。
  path_mapping: # cd2中的路径映射到plex中
    enable: true
    rules:
      - from: /115/Public
        to: /share/SSD1T/03cd2/115
emby:
  host: https://your.emby.com
  api_key: your-emby-api-key
  isfile_based_scanning: true
  path_mapping: # cd2中的路径映射到emby中
    enable: true
    rules:
      - from: /115/Public
        to: /mnt/user/CloudDrive/115
MONITOR_FOLDER:
  /115/Public/电视/国产动漫剧:
    blacklist: ['/115/Public/tmp'] # 黑名单，不会被扫描
    overwrite_db: false #构建数据库时，对数据库中已存在的时间采用覆盖模式（防止数据库中的时间戳太旧）
