servers: ['plex','emby'] # You can only keep one ['plex'] or ['emby'].
plex:
  host: http://127.0.0.1:32400
  token: plex token
emby:
  host: http://127.0.0.1:8096
  api_key: emby api_key 
  path_mapping:
    # If your Plex and Emby are on separate servers,
    # you may need to map the paths accordingly.
    enable: true
    rules:
      - from: /share/SSD1T/03cd2/aliyun
        to: /mnt/user/CloudDrive/aliyundrive
MONITOR_FOLDER:
  # NOTE! The docker container will create a process for each
  # folder to monitor, so please do not add too many folders.
  - /share/SSD1T/03cd2/aliyun/Movies
  - /share/SSD1T/03cd2/aliyun/TVs