flask:
    # webui 监听地址和端口
    host: 0.0.0.0
    port: 2024
    secret_key: "secret_key" # 无需修改
    # 登录页面的用户名和密码
    username: "admin"
    password: "admin"
    # 调度器的配置，以下参数均无需修改
    scheduler:
        timezone: "Asia/Shanghai" # 时区
        api_enabled: true # 是否启用API
        default_interval: 1d # 默认执行间隔，单位m/h/d，分别对应分钟/小时/天，更多请参考https://github.com/wroberts/pytimeparse 程序暂未调用此参数
databases:
    # 程序所需要的数据库配置,如果你不懂参数的含义，请不要修改
    redis:
        host: 127.0.0.1
        port: 6379
        username: "default"
        password: "helloworld"
        db: 0
        socket_timeout: 10 # 连接超时时间
        pool_enabled: true # 是否启用连接池
        # celery配置
        celery_broker_db: 1
        celery_result_db: 2
    sqlite:
        path: "app.sqlite" # /config路径下的sqlite数据库文件路径
        pool_timeout: 10 # 连接超时时间
        pool_size: 5 # 连接池大小

clouddrive2:
    # clouddrive2配置
    host: http://xxx.xxx.xxx.xxx:19798
    username: xxx@mail.com
    password: xxxxx
media_servers:
    # 媒体服务器配置
    plex:
        enabled: true # 若不使用plex，则设置为false
        host: http://xxx.xxxx.xxx.xxx:32400
        token: plex_token_here
        isfile_based_scanning: true # 基于文件的扫描，目前观望此参数是否应弃用
        path_mapping:
            # 从clouddrive2的路径映射到媒体服务器内部的路径
            enabled: true # 若不使用路径映射，则设置为false
            rules:
              - from: /115/Public
                to: /share/SSD1T/03cd2/115
    emby:
        enabled: true # 若不使用emby，则设置为false
        host: https://emby.example.com
        api_key: emby_api_key_here
        isfile_based_scanning: true
        path_mapping:
            enabled: true
            rules:
              - from: /115/Public
                to: /mnt/user/CloudDrive/115
