servers: ['plex','emby'] # 可只保留一个['plex']或者['emby']
plex:
  host: http://127.0.0.1:32400
  token: 你的plex token
emby:
  host: http://127.0.0.1:8096
  api_key: 你的emby api_key 
MONITOR_FOLDER:
  - /mnt/user/CloudDrive/115/电视
  - /mnt/user/CloudDrive/115/电影
  - /mnt/user/CloudDrive/aliyundrive/电视
  - /mnt/user/CloudDrive/aliyundrive/电影意