services:
  mtimebasedscan4plex:
    image: zfhxi/mtimebasedscan4plex:latest
    container_name: mtimebasedscan4plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /mnt/user/CloudDrive:/mnt/user/CloudDrive:rslave # cd2挂载到本地