#!/bin/bash

# 启动 logrotate 并定时运行
while true; do
    /usr/sbin/logrotate /etc/logrotate.d/mtimebasedscan4plex
    sleep 10m
done &

# 如果宿主机的目录中没有配置文件，就从镜像中复制
if [ ! -f /config/config.yaml ]; then
    cp /template/config.yaml /config/config.yaml
fi
cp /template/config.yaml /config/config_template.yaml


launch(){
    # 运行 Python 脚本
    touch /app/output.log && echo -e "\n日志记录开始："
    cd /app && python -u main.py true

    # 创建计划任务
    echo -e "\n创建监测计划任务..."
    cd /app && python -u cron.py
    crond
}

launch >> /app/output.log 2>&1 &
tail -f /app/output.log
