name: partialpathscanner Builder
on:
    workflow_dispatch:
    push:
        tags:
          - 'v*'
env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
    Docker-build:
        runs-on: ubuntu-latest
        name: Build Docker Image
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set Up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set Up Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ env.DOCKERHUB_USERNAME }}
                password: ${{ env.DOCKERHUB_TOKEN }}

          - name: partialpathscanner
            run: |
                docker buildx build --platform linux/amd64 -t $DOCKERHUB_USERNAME/partialpathscanner:beta -t $DOCKERHUB_USERNAME/partialpathscanner:${GITHUB_SHA::7} -f Dockerfile . --push
